services:
  backend:
    build: .
    ports:
      - "3001:3001" # Memetakan port 3001 container ke port 3001 host
    environment:
      DATABASE_URL: "mysql://api:8T1k3u2w8kqj+FXfpMytoQ==@mysql-dev:3306/api_dev"
      PORT: "3001"
    depends_on:
      mysql-dev:
        condition: service_healthy
    restart: unless-stopped
  mysql-dev:
    image: mysql:8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p'root_password_change_me'"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root_password_change_me 
      MYSQL_DATABASE: api_dev
      MYSQL_USER: api
      MYSQL_PASSWORD: ${DB_PASSWORD} # This will be read from the .env file
    ports:
      - 4329:3306
    volumes:
      - mysql-dev-data:/var/lib/mysql
  mysql-test:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_change_me
      MYSQL_DATABASE: api_test
      MYSQL_USER: api
      MYSQL_PASSWORD: password
    ports:
      - 4328:3306

volumes:
  mysql-dev-data:
