services:
  backend:
    build: .
    ports:
      - "3001:3001" # Memetakan port 3001 container ke port 3001 host
    env_file:
      - ./.env
    depends_on:
      - mysql-dev
    restart: unless-stopped
  mysql-dev:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_change_me 
      MYSQL_DATABASE: api_dev
      MYSQL_USER: api
      MYSQL_PASSWORD: ${DB_PASSWORD} # This will be read from the .env file
    ports:
      - 4329:3306
    volumes:
      - mysql-dev-data:/var/lib/mysql
  mysql-test:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_change_me
      MYSQL_DATABASE: api_test
      MYSQL_USER: api
      MYSQL_PASSWORD: password
    ports:
      - 4328:3306

volumes:
  mysql-dev-data:
